# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Server/Server.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from Article import Article_pb2 as Article_dot_Article__pb2
from Client import Client_pb2 as Client_dot_Client__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Server/Server.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13Server/Server.proto\x1a\x15\x41rticle/Article.proto\x1a\x13\x43lient/Client.proto\"\x84\x01\n\x06Server\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12!\n\x0fhosted_articles\x18\x03 \x03(\x0b\x32\x08.Article\x12\x1c\n\x0bsubscribers\x18\x04 \x03(\x0b\x32\x07.Client\x12\x1a\n\tclientele\x18\x05 \x03(\x0b\x32\x07.Clientb\x06proto3'
  ,
  dependencies=[Article_dot_Article__pb2.DESCRIPTOR,Client_dot_Client__pb2.DESCRIPTOR,])




_SERVER = _descriptor.Descriptor(
  name='Server',
  full_name='Server',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='Server.address', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='Server.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hosted_articles', full_name='Server.hosted_articles', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='subscribers', full_name='Server.subscribers', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='clientele', full_name='Server.clientele', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=200,
)

_SERVER.fields_by_name['hosted_articles'].message_type = Article_dot_Article__pb2._ARTICLE
_SERVER.fields_by_name['subscribers'].message_type = Client_dot_Client__pb2._CLIENT
_SERVER.fields_by_name['clientele'].message_type = Client_dot_Client__pb2._CLIENT
DESCRIPTOR.message_types_by_name['Server'] = _SERVER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Server = _reflection.GeneratedProtocolMessageType('Server', (_message.Message,), {
  'DESCRIPTOR' : _SERVER,
  '__module__' : 'Server.Server_pb2'
  # @@protoc_insertion_point(class_scope:Server)
  })
_sym_db.RegisterMessage(Server)


# @@protoc_insertion_point(module_scope)
