// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Server/Server.proto

public final class ServerOuterClass {
  private ServerOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ServerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Server)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string address = 1;</code>
     * @return The address.
     */
    java.lang.String getAddress();
    /**
     * <code>string address = 1;</code>
     * @return The bytes for address.
     */
    com.google.protobuf.ByteString
        getAddressBytes();

    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>repeated .Article hosted_articles = 3;</code>
     */
    java.util.List<ArticleOuterClass.Article> 
        getHostedArticlesList();
    /**
     * <code>repeated .Article hosted_articles = 3;</code>
     */
    ArticleOuterClass.Article getHostedArticles(int index);
    /**
     * <code>repeated .Article hosted_articles = 3;</code>
     */
    int getHostedArticlesCount();
    /**
     * <code>repeated .Article hosted_articles = 3;</code>
     */
    java.util.List<? extends ArticleOuterClass.ArticleOrBuilder> 
        getHostedArticlesOrBuilderList();
    /**
     * <code>repeated .Article hosted_articles = 3;</code>
     */
    ArticleOuterClass.ArticleOrBuilder getHostedArticlesOrBuilder(
        int index);

    /**
     * <code>repeated .Client subscribers = 4;</code>
     */
    java.util.List<ClientOuterClass.Client> 
        getSubscribersList();
    /**
     * <code>repeated .Client subscribers = 4;</code>
     */
    ClientOuterClass.Client getSubscribers(int index);
    /**
     * <code>repeated .Client subscribers = 4;</code>
     */
    int getSubscribersCount();
    /**
     * <code>repeated .Client subscribers = 4;</code>
     */
    java.util.List<? extends ClientOuterClass.ClientOrBuilder> 
        getSubscribersOrBuilderList();
    /**
     * <code>repeated .Client subscribers = 4;</code>
     */
    ClientOuterClass.ClientOrBuilder getSubscribersOrBuilder(
        int index);

    /**
     * <code>repeated .Client clientele = 5;</code>
     */
    java.util.List<ClientOuterClass.Client> 
        getClienteleList();
    /**
     * <code>repeated .Client clientele = 5;</code>
     */
    ClientOuterClass.Client getClientele(int index);
    /**
     * <code>repeated .Client clientele = 5;</code>
     */
    int getClienteleCount();
    /**
     * <code>repeated .Client clientele = 5;</code>
     */
    java.util.List<? extends ClientOuterClass.ClientOrBuilder> 
        getClienteleOrBuilderList();
    /**
     * <code>repeated .Client clientele = 5;</code>
     */
    ClientOuterClass.ClientOrBuilder getClienteleOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Server}
   */
  public static final class Server extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Server)
      ServerOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Server.newBuilder() to construct.
    private Server(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Server() {
      address_ = "";
      name_ = "";
      hostedArticles_ = java.util.Collections.emptyList();
      subscribers_ = java.util.Collections.emptyList();
      clientele_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Server();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Server(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              address_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                hostedArticles_ = new java.util.ArrayList<ArticleOuterClass.Article>();
                mutable_bitField0_ |= 0x00000001;
              }
              hostedArticles_.add(
                  input.readMessage(ArticleOuterClass.Article.parser(), extensionRegistry));
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                subscribers_ = new java.util.ArrayList<ClientOuterClass.Client>();
                mutable_bitField0_ |= 0x00000002;
              }
              subscribers_.add(
                  input.readMessage(ClientOuterClass.Client.parser(), extensionRegistry));
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000004) != 0)) {
                clientele_ = new java.util.ArrayList<ClientOuterClass.Client>();
                mutable_bitField0_ |= 0x00000004;
              }
              clientele_.add(
                  input.readMessage(ClientOuterClass.Client.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          hostedArticles_ = java.util.Collections.unmodifiableList(hostedArticles_);
        }
        if (((mutable_bitField0_ & 0x00000002) != 0)) {
          subscribers_ = java.util.Collections.unmodifiableList(subscribers_);
        }
        if (((mutable_bitField0_ & 0x00000004) != 0)) {
          clientele_ = java.util.Collections.unmodifiableList(clientele_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ServerOuterClass.internal_static_Server_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ServerOuterClass.internal_static_Server_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ServerOuterClass.Server.class, ServerOuterClass.Server.Builder.class);
    }

    public static final int ADDRESS_FIELD_NUMBER = 1;
    private volatile java.lang.Object address_;
    /**
     * <code>string address = 1;</code>
     * @return The address.
     */
    @java.lang.Override
    public java.lang.String getAddress() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        address_ = s;
        return s;
      }
    }
    /**
     * <code>string address = 1;</code>
     * @return The bytes for address.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAddressBytes() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HOSTED_ARTICLES_FIELD_NUMBER = 3;
    private java.util.List<ArticleOuterClass.Article> hostedArticles_;
    /**
     * <code>repeated .Article hosted_articles = 3;</code>
     */
    @java.lang.Override
    public java.util.List<ArticleOuterClass.Article> getHostedArticlesList() {
      return hostedArticles_;
    }
    /**
     * <code>repeated .Article hosted_articles = 3;</code>
     */
    @java.lang.Override
    public java.util.List<? extends ArticleOuterClass.ArticleOrBuilder> 
        getHostedArticlesOrBuilderList() {
      return hostedArticles_;
    }
    /**
     * <code>repeated .Article hosted_articles = 3;</code>
     */
    @java.lang.Override
    public int getHostedArticlesCount() {
      return hostedArticles_.size();
    }
    /**
     * <code>repeated .Article hosted_articles = 3;</code>
     */
    @java.lang.Override
    public ArticleOuterClass.Article getHostedArticles(int index) {
      return hostedArticles_.get(index);
    }
    /**
     * <code>repeated .Article hosted_articles = 3;</code>
     */
    @java.lang.Override
    public ArticleOuterClass.ArticleOrBuilder getHostedArticlesOrBuilder(
        int index) {
      return hostedArticles_.get(index);
    }

    public static final int SUBSCRIBERS_FIELD_NUMBER = 4;
    private java.util.List<ClientOuterClass.Client> subscribers_;
    /**
     * <code>repeated .Client subscribers = 4;</code>
     */
    @java.lang.Override
    public java.util.List<ClientOuterClass.Client> getSubscribersList() {
      return subscribers_;
    }
    /**
     * <code>repeated .Client subscribers = 4;</code>
     */
    @java.lang.Override
    public java.util.List<? extends ClientOuterClass.ClientOrBuilder> 
        getSubscribersOrBuilderList() {
      return subscribers_;
    }
    /**
     * <code>repeated .Client subscribers = 4;</code>
     */
    @java.lang.Override
    public int getSubscribersCount() {
      return subscribers_.size();
    }
    /**
     * <code>repeated .Client subscribers = 4;</code>
     */
    @java.lang.Override
    public ClientOuterClass.Client getSubscribers(int index) {
      return subscribers_.get(index);
    }
    /**
     * <code>repeated .Client subscribers = 4;</code>
     */
    @java.lang.Override
    public ClientOuterClass.ClientOrBuilder getSubscribersOrBuilder(
        int index) {
      return subscribers_.get(index);
    }

    public static final int CLIENTELE_FIELD_NUMBER = 5;
    private java.util.List<ClientOuterClass.Client> clientele_;
    /**
     * <code>repeated .Client clientele = 5;</code>
     */
    @java.lang.Override
    public java.util.List<ClientOuterClass.Client> getClienteleList() {
      return clientele_;
    }
    /**
     * <code>repeated .Client clientele = 5;</code>
     */
    @java.lang.Override
    public java.util.List<? extends ClientOuterClass.ClientOrBuilder> 
        getClienteleOrBuilderList() {
      return clientele_;
    }
    /**
     * <code>repeated .Client clientele = 5;</code>
     */
    @java.lang.Override
    public int getClienteleCount() {
      return clientele_.size();
    }
    /**
     * <code>repeated .Client clientele = 5;</code>
     */
    @java.lang.Override
    public ClientOuterClass.Client getClientele(int index) {
      return clientele_.get(index);
    }
    /**
     * <code>repeated .Client clientele = 5;</code>
     */
    @java.lang.Override
    public ClientOuterClass.ClientOrBuilder getClienteleOrBuilder(
        int index) {
      return clientele_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getAddressBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, address_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      for (int i = 0; i < hostedArticles_.size(); i++) {
        output.writeMessage(3, hostedArticles_.get(i));
      }
      for (int i = 0; i < subscribers_.size(); i++) {
        output.writeMessage(4, subscribers_.get(i));
      }
      for (int i = 0; i < clientele_.size(); i++) {
        output.writeMessage(5, clientele_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getAddressBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, address_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      for (int i = 0; i < hostedArticles_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, hostedArticles_.get(i));
      }
      for (int i = 0; i < subscribers_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, subscribers_.get(i));
      }
      for (int i = 0; i < clientele_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, clientele_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ServerOuterClass.Server)) {
        return super.equals(obj);
      }
      ServerOuterClass.Server other = (ServerOuterClass.Server) obj;

      if (!getAddress()
          .equals(other.getAddress())) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!getHostedArticlesList()
          .equals(other.getHostedArticlesList())) return false;
      if (!getSubscribersList()
          .equals(other.getSubscribersList())) return false;
      if (!getClienteleList()
          .equals(other.getClienteleList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddress().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      if (getHostedArticlesCount() > 0) {
        hash = (37 * hash) + HOSTED_ARTICLES_FIELD_NUMBER;
        hash = (53 * hash) + getHostedArticlesList().hashCode();
      }
      if (getSubscribersCount() > 0) {
        hash = (37 * hash) + SUBSCRIBERS_FIELD_NUMBER;
        hash = (53 * hash) + getSubscribersList().hashCode();
      }
      if (getClienteleCount() > 0) {
        hash = (37 * hash) + CLIENTELE_FIELD_NUMBER;
        hash = (53 * hash) + getClienteleList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ServerOuterClass.Server parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ServerOuterClass.Server parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ServerOuterClass.Server parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ServerOuterClass.Server parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ServerOuterClass.Server parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ServerOuterClass.Server parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ServerOuterClass.Server parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ServerOuterClass.Server parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ServerOuterClass.Server parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ServerOuterClass.Server parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ServerOuterClass.Server parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ServerOuterClass.Server parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ServerOuterClass.Server prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Server}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Server)
        ServerOuterClass.ServerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ServerOuterClass.internal_static_Server_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ServerOuterClass.internal_static_Server_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ServerOuterClass.Server.class, ServerOuterClass.Server.Builder.class);
      }

      // Construct using ServerOuterClass.Server.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getHostedArticlesFieldBuilder();
          getSubscribersFieldBuilder();
          getClienteleFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        address_ = "";

        name_ = "";

        if (hostedArticlesBuilder_ == null) {
          hostedArticles_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          hostedArticlesBuilder_.clear();
        }
        if (subscribersBuilder_ == null) {
          subscribers_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          subscribersBuilder_.clear();
        }
        if (clienteleBuilder_ == null) {
          clientele_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          clienteleBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ServerOuterClass.internal_static_Server_descriptor;
      }

      @java.lang.Override
      public ServerOuterClass.Server getDefaultInstanceForType() {
        return ServerOuterClass.Server.getDefaultInstance();
      }

      @java.lang.Override
      public ServerOuterClass.Server build() {
        ServerOuterClass.Server result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ServerOuterClass.Server buildPartial() {
        ServerOuterClass.Server result = new ServerOuterClass.Server(this);
        int from_bitField0_ = bitField0_;
        result.address_ = address_;
        result.name_ = name_;
        if (hostedArticlesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            hostedArticles_ = java.util.Collections.unmodifiableList(hostedArticles_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.hostedArticles_ = hostedArticles_;
        } else {
          result.hostedArticles_ = hostedArticlesBuilder_.build();
        }
        if (subscribersBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0)) {
            subscribers_ = java.util.Collections.unmodifiableList(subscribers_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.subscribers_ = subscribers_;
        } else {
          result.subscribers_ = subscribersBuilder_.build();
        }
        if (clienteleBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0)) {
            clientele_ = java.util.Collections.unmodifiableList(clientele_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.clientele_ = clientele_;
        } else {
          result.clientele_ = clienteleBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ServerOuterClass.Server) {
          return mergeFrom((ServerOuterClass.Server)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ServerOuterClass.Server other) {
        if (other == ServerOuterClass.Server.getDefaultInstance()) return this;
        if (!other.getAddress().isEmpty()) {
          address_ = other.address_;
          onChanged();
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (hostedArticlesBuilder_ == null) {
          if (!other.hostedArticles_.isEmpty()) {
            if (hostedArticles_.isEmpty()) {
              hostedArticles_ = other.hostedArticles_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureHostedArticlesIsMutable();
              hostedArticles_.addAll(other.hostedArticles_);
            }
            onChanged();
          }
        } else {
          if (!other.hostedArticles_.isEmpty()) {
            if (hostedArticlesBuilder_.isEmpty()) {
              hostedArticlesBuilder_.dispose();
              hostedArticlesBuilder_ = null;
              hostedArticles_ = other.hostedArticles_;
              bitField0_ = (bitField0_ & ~0x00000001);
              hostedArticlesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getHostedArticlesFieldBuilder() : null;
            } else {
              hostedArticlesBuilder_.addAllMessages(other.hostedArticles_);
            }
          }
        }
        if (subscribersBuilder_ == null) {
          if (!other.subscribers_.isEmpty()) {
            if (subscribers_.isEmpty()) {
              subscribers_ = other.subscribers_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureSubscribersIsMutable();
              subscribers_.addAll(other.subscribers_);
            }
            onChanged();
          }
        } else {
          if (!other.subscribers_.isEmpty()) {
            if (subscribersBuilder_.isEmpty()) {
              subscribersBuilder_.dispose();
              subscribersBuilder_ = null;
              subscribers_ = other.subscribers_;
              bitField0_ = (bitField0_ & ~0x00000002);
              subscribersBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getSubscribersFieldBuilder() : null;
            } else {
              subscribersBuilder_.addAllMessages(other.subscribers_);
            }
          }
        }
        if (clienteleBuilder_ == null) {
          if (!other.clientele_.isEmpty()) {
            if (clientele_.isEmpty()) {
              clientele_ = other.clientele_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureClienteleIsMutable();
              clientele_.addAll(other.clientele_);
            }
            onChanged();
          }
        } else {
          if (!other.clientele_.isEmpty()) {
            if (clienteleBuilder_.isEmpty()) {
              clienteleBuilder_.dispose();
              clienteleBuilder_ = null;
              clientele_ = other.clientele_;
              bitField0_ = (bitField0_ & ~0x00000004);
              clienteleBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getClienteleFieldBuilder() : null;
            } else {
              clienteleBuilder_.addAllMessages(other.clientele_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ServerOuterClass.Server parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ServerOuterClass.Server) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object address_ = "";
      /**
       * <code>string address = 1;</code>
       * @return The address.
       */
      public java.lang.String getAddress() {
        java.lang.Object ref = address_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          address_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string address = 1;</code>
       * @return The bytes for address.
       */
      public com.google.protobuf.ByteString
          getAddressBytes() {
        java.lang.Object ref = address_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          address_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string address = 1;</code>
       * @param value The address to set.
       * @return This builder for chaining.
       */
      public Builder setAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        address_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string address = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAddress() {
        
        address_ = getDefaultInstance().getAddress();
        onChanged();
        return this;
      }
      /**
       * <code>string address = 1;</code>
       * @param value The bytes for address to set.
       * @return This builder for chaining.
       */
      public Builder setAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        address_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.util.List<ArticleOuterClass.Article> hostedArticles_ =
        java.util.Collections.emptyList();
      private void ensureHostedArticlesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          hostedArticles_ = new java.util.ArrayList<ArticleOuterClass.Article>(hostedArticles_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          ArticleOuterClass.Article, ArticleOuterClass.Article.Builder, ArticleOuterClass.ArticleOrBuilder> hostedArticlesBuilder_;

      /**
       * <code>repeated .Article hosted_articles = 3;</code>
       */
      public java.util.List<ArticleOuterClass.Article> getHostedArticlesList() {
        if (hostedArticlesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(hostedArticles_);
        } else {
          return hostedArticlesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Article hosted_articles = 3;</code>
       */
      public int getHostedArticlesCount() {
        if (hostedArticlesBuilder_ == null) {
          return hostedArticles_.size();
        } else {
          return hostedArticlesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Article hosted_articles = 3;</code>
       */
      public ArticleOuterClass.Article getHostedArticles(int index) {
        if (hostedArticlesBuilder_ == null) {
          return hostedArticles_.get(index);
        } else {
          return hostedArticlesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Article hosted_articles = 3;</code>
       */
      public Builder setHostedArticles(
          int index, ArticleOuterClass.Article value) {
        if (hostedArticlesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHostedArticlesIsMutable();
          hostedArticles_.set(index, value);
          onChanged();
        } else {
          hostedArticlesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Article hosted_articles = 3;</code>
       */
      public Builder setHostedArticles(
          int index, ArticleOuterClass.Article.Builder builderForValue) {
        if (hostedArticlesBuilder_ == null) {
          ensureHostedArticlesIsMutable();
          hostedArticles_.set(index, builderForValue.build());
          onChanged();
        } else {
          hostedArticlesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Article hosted_articles = 3;</code>
       */
      public Builder addHostedArticles(ArticleOuterClass.Article value) {
        if (hostedArticlesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHostedArticlesIsMutable();
          hostedArticles_.add(value);
          onChanged();
        } else {
          hostedArticlesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Article hosted_articles = 3;</code>
       */
      public Builder addHostedArticles(
          int index, ArticleOuterClass.Article value) {
        if (hostedArticlesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHostedArticlesIsMutable();
          hostedArticles_.add(index, value);
          onChanged();
        } else {
          hostedArticlesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Article hosted_articles = 3;</code>
       */
      public Builder addHostedArticles(
          ArticleOuterClass.Article.Builder builderForValue) {
        if (hostedArticlesBuilder_ == null) {
          ensureHostedArticlesIsMutable();
          hostedArticles_.add(builderForValue.build());
          onChanged();
        } else {
          hostedArticlesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Article hosted_articles = 3;</code>
       */
      public Builder addHostedArticles(
          int index, ArticleOuterClass.Article.Builder builderForValue) {
        if (hostedArticlesBuilder_ == null) {
          ensureHostedArticlesIsMutable();
          hostedArticles_.add(index, builderForValue.build());
          onChanged();
        } else {
          hostedArticlesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Article hosted_articles = 3;</code>
       */
      public Builder addAllHostedArticles(
          java.lang.Iterable<? extends ArticleOuterClass.Article> values) {
        if (hostedArticlesBuilder_ == null) {
          ensureHostedArticlesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, hostedArticles_);
          onChanged();
        } else {
          hostedArticlesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Article hosted_articles = 3;</code>
       */
      public Builder clearHostedArticles() {
        if (hostedArticlesBuilder_ == null) {
          hostedArticles_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          hostedArticlesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Article hosted_articles = 3;</code>
       */
      public Builder removeHostedArticles(int index) {
        if (hostedArticlesBuilder_ == null) {
          ensureHostedArticlesIsMutable();
          hostedArticles_.remove(index);
          onChanged();
        } else {
          hostedArticlesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Article hosted_articles = 3;</code>
       */
      public ArticleOuterClass.Article.Builder getHostedArticlesBuilder(
          int index) {
        return getHostedArticlesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Article hosted_articles = 3;</code>
       */
      public ArticleOuterClass.ArticleOrBuilder getHostedArticlesOrBuilder(
          int index) {
        if (hostedArticlesBuilder_ == null) {
          return hostedArticles_.get(index);  } else {
          return hostedArticlesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Article hosted_articles = 3;</code>
       */
      public java.util.List<? extends ArticleOuterClass.ArticleOrBuilder> 
           getHostedArticlesOrBuilderList() {
        if (hostedArticlesBuilder_ != null) {
          return hostedArticlesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(hostedArticles_);
        }
      }
      /**
       * <code>repeated .Article hosted_articles = 3;</code>
       */
      public ArticleOuterClass.Article.Builder addHostedArticlesBuilder() {
        return getHostedArticlesFieldBuilder().addBuilder(
            ArticleOuterClass.Article.getDefaultInstance());
      }
      /**
       * <code>repeated .Article hosted_articles = 3;</code>
       */
      public ArticleOuterClass.Article.Builder addHostedArticlesBuilder(
          int index) {
        return getHostedArticlesFieldBuilder().addBuilder(
            index, ArticleOuterClass.Article.getDefaultInstance());
      }
      /**
       * <code>repeated .Article hosted_articles = 3;</code>
       */
      public java.util.List<ArticleOuterClass.Article.Builder> 
           getHostedArticlesBuilderList() {
        return getHostedArticlesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          ArticleOuterClass.Article, ArticleOuterClass.Article.Builder, ArticleOuterClass.ArticleOrBuilder> 
          getHostedArticlesFieldBuilder() {
        if (hostedArticlesBuilder_ == null) {
          hostedArticlesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              ArticleOuterClass.Article, ArticleOuterClass.Article.Builder, ArticleOuterClass.ArticleOrBuilder>(
                  hostedArticles_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          hostedArticles_ = null;
        }
        return hostedArticlesBuilder_;
      }

      private java.util.List<ClientOuterClass.Client> subscribers_ =
        java.util.Collections.emptyList();
      private void ensureSubscribersIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          subscribers_ = new java.util.ArrayList<ClientOuterClass.Client>(subscribers_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          ClientOuterClass.Client, ClientOuterClass.Client.Builder, ClientOuterClass.ClientOrBuilder> subscribersBuilder_;

      /**
       * <code>repeated .Client subscribers = 4;</code>
       */
      public java.util.List<ClientOuterClass.Client> getSubscribersList() {
        if (subscribersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(subscribers_);
        } else {
          return subscribersBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Client subscribers = 4;</code>
       */
      public int getSubscribersCount() {
        if (subscribersBuilder_ == null) {
          return subscribers_.size();
        } else {
          return subscribersBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Client subscribers = 4;</code>
       */
      public ClientOuterClass.Client getSubscribers(int index) {
        if (subscribersBuilder_ == null) {
          return subscribers_.get(index);
        } else {
          return subscribersBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Client subscribers = 4;</code>
       */
      public Builder setSubscribers(
          int index, ClientOuterClass.Client value) {
        if (subscribersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSubscribersIsMutable();
          subscribers_.set(index, value);
          onChanged();
        } else {
          subscribersBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Client subscribers = 4;</code>
       */
      public Builder setSubscribers(
          int index, ClientOuterClass.Client.Builder builderForValue) {
        if (subscribersBuilder_ == null) {
          ensureSubscribersIsMutable();
          subscribers_.set(index, builderForValue.build());
          onChanged();
        } else {
          subscribersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Client subscribers = 4;</code>
       */
      public Builder addSubscribers(ClientOuterClass.Client value) {
        if (subscribersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSubscribersIsMutable();
          subscribers_.add(value);
          onChanged();
        } else {
          subscribersBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Client subscribers = 4;</code>
       */
      public Builder addSubscribers(
          int index, ClientOuterClass.Client value) {
        if (subscribersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSubscribersIsMutable();
          subscribers_.add(index, value);
          onChanged();
        } else {
          subscribersBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Client subscribers = 4;</code>
       */
      public Builder addSubscribers(
          ClientOuterClass.Client.Builder builderForValue) {
        if (subscribersBuilder_ == null) {
          ensureSubscribersIsMutable();
          subscribers_.add(builderForValue.build());
          onChanged();
        } else {
          subscribersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Client subscribers = 4;</code>
       */
      public Builder addSubscribers(
          int index, ClientOuterClass.Client.Builder builderForValue) {
        if (subscribersBuilder_ == null) {
          ensureSubscribersIsMutable();
          subscribers_.add(index, builderForValue.build());
          onChanged();
        } else {
          subscribersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Client subscribers = 4;</code>
       */
      public Builder addAllSubscribers(
          java.lang.Iterable<? extends ClientOuterClass.Client> values) {
        if (subscribersBuilder_ == null) {
          ensureSubscribersIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, subscribers_);
          onChanged();
        } else {
          subscribersBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Client subscribers = 4;</code>
       */
      public Builder clearSubscribers() {
        if (subscribersBuilder_ == null) {
          subscribers_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          subscribersBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Client subscribers = 4;</code>
       */
      public Builder removeSubscribers(int index) {
        if (subscribersBuilder_ == null) {
          ensureSubscribersIsMutable();
          subscribers_.remove(index);
          onChanged();
        } else {
          subscribersBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Client subscribers = 4;</code>
       */
      public ClientOuterClass.Client.Builder getSubscribersBuilder(
          int index) {
        return getSubscribersFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Client subscribers = 4;</code>
       */
      public ClientOuterClass.ClientOrBuilder getSubscribersOrBuilder(
          int index) {
        if (subscribersBuilder_ == null) {
          return subscribers_.get(index);  } else {
          return subscribersBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Client subscribers = 4;</code>
       */
      public java.util.List<? extends ClientOuterClass.ClientOrBuilder> 
           getSubscribersOrBuilderList() {
        if (subscribersBuilder_ != null) {
          return subscribersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(subscribers_);
        }
      }
      /**
       * <code>repeated .Client subscribers = 4;</code>
       */
      public ClientOuterClass.Client.Builder addSubscribersBuilder() {
        return getSubscribersFieldBuilder().addBuilder(
            ClientOuterClass.Client.getDefaultInstance());
      }
      /**
       * <code>repeated .Client subscribers = 4;</code>
       */
      public ClientOuterClass.Client.Builder addSubscribersBuilder(
          int index) {
        return getSubscribersFieldBuilder().addBuilder(
            index, ClientOuterClass.Client.getDefaultInstance());
      }
      /**
       * <code>repeated .Client subscribers = 4;</code>
       */
      public java.util.List<ClientOuterClass.Client.Builder> 
           getSubscribersBuilderList() {
        return getSubscribersFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          ClientOuterClass.Client, ClientOuterClass.Client.Builder, ClientOuterClass.ClientOrBuilder> 
          getSubscribersFieldBuilder() {
        if (subscribersBuilder_ == null) {
          subscribersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              ClientOuterClass.Client, ClientOuterClass.Client.Builder, ClientOuterClass.ClientOrBuilder>(
                  subscribers_,
                  ((bitField0_ & 0x00000002) != 0),
                  getParentForChildren(),
                  isClean());
          subscribers_ = null;
        }
        return subscribersBuilder_;
      }

      private java.util.List<ClientOuterClass.Client> clientele_ =
        java.util.Collections.emptyList();
      private void ensureClienteleIsMutable() {
        if (!((bitField0_ & 0x00000004) != 0)) {
          clientele_ = new java.util.ArrayList<ClientOuterClass.Client>(clientele_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          ClientOuterClass.Client, ClientOuterClass.Client.Builder, ClientOuterClass.ClientOrBuilder> clienteleBuilder_;

      /**
       * <code>repeated .Client clientele = 5;</code>
       */
      public java.util.List<ClientOuterClass.Client> getClienteleList() {
        if (clienteleBuilder_ == null) {
          return java.util.Collections.unmodifiableList(clientele_);
        } else {
          return clienteleBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Client clientele = 5;</code>
       */
      public int getClienteleCount() {
        if (clienteleBuilder_ == null) {
          return clientele_.size();
        } else {
          return clienteleBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Client clientele = 5;</code>
       */
      public ClientOuterClass.Client getClientele(int index) {
        if (clienteleBuilder_ == null) {
          return clientele_.get(index);
        } else {
          return clienteleBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Client clientele = 5;</code>
       */
      public Builder setClientele(
          int index, ClientOuterClass.Client value) {
        if (clienteleBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureClienteleIsMutable();
          clientele_.set(index, value);
          onChanged();
        } else {
          clienteleBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Client clientele = 5;</code>
       */
      public Builder setClientele(
          int index, ClientOuterClass.Client.Builder builderForValue) {
        if (clienteleBuilder_ == null) {
          ensureClienteleIsMutable();
          clientele_.set(index, builderForValue.build());
          onChanged();
        } else {
          clienteleBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Client clientele = 5;</code>
       */
      public Builder addClientele(ClientOuterClass.Client value) {
        if (clienteleBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureClienteleIsMutable();
          clientele_.add(value);
          onChanged();
        } else {
          clienteleBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Client clientele = 5;</code>
       */
      public Builder addClientele(
          int index, ClientOuterClass.Client value) {
        if (clienteleBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureClienteleIsMutable();
          clientele_.add(index, value);
          onChanged();
        } else {
          clienteleBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Client clientele = 5;</code>
       */
      public Builder addClientele(
          ClientOuterClass.Client.Builder builderForValue) {
        if (clienteleBuilder_ == null) {
          ensureClienteleIsMutable();
          clientele_.add(builderForValue.build());
          onChanged();
        } else {
          clienteleBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Client clientele = 5;</code>
       */
      public Builder addClientele(
          int index, ClientOuterClass.Client.Builder builderForValue) {
        if (clienteleBuilder_ == null) {
          ensureClienteleIsMutable();
          clientele_.add(index, builderForValue.build());
          onChanged();
        } else {
          clienteleBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Client clientele = 5;</code>
       */
      public Builder addAllClientele(
          java.lang.Iterable<? extends ClientOuterClass.Client> values) {
        if (clienteleBuilder_ == null) {
          ensureClienteleIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, clientele_);
          onChanged();
        } else {
          clienteleBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Client clientele = 5;</code>
       */
      public Builder clearClientele() {
        if (clienteleBuilder_ == null) {
          clientele_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          clienteleBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Client clientele = 5;</code>
       */
      public Builder removeClientele(int index) {
        if (clienteleBuilder_ == null) {
          ensureClienteleIsMutable();
          clientele_.remove(index);
          onChanged();
        } else {
          clienteleBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Client clientele = 5;</code>
       */
      public ClientOuterClass.Client.Builder getClienteleBuilder(
          int index) {
        return getClienteleFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Client clientele = 5;</code>
       */
      public ClientOuterClass.ClientOrBuilder getClienteleOrBuilder(
          int index) {
        if (clienteleBuilder_ == null) {
          return clientele_.get(index);  } else {
          return clienteleBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Client clientele = 5;</code>
       */
      public java.util.List<? extends ClientOuterClass.ClientOrBuilder> 
           getClienteleOrBuilderList() {
        if (clienteleBuilder_ != null) {
          return clienteleBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(clientele_);
        }
      }
      /**
       * <code>repeated .Client clientele = 5;</code>
       */
      public ClientOuterClass.Client.Builder addClienteleBuilder() {
        return getClienteleFieldBuilder().addBuilder(
            ClientOuterClass.Client.getDefaultInstance());
      }
      /**
       * <code>repeated .Client clientele = 5;</code>
       */
      public ClientOuterClass.Client.Builder addClienteleBuilder(
          int index) {
        return getClienteleFieldBuilder().addBuilder(
            index, ClientOuterClass.Client.getDefaultInstance());
      }
      /**
       * <code>repeated .Client clientele = 5;</code>
       */
      public java.util.List<ClientOuterClass.Client.Builder> 
           getClienteleBuilderList() {
        return getClienteleFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          ClientOuterClass.Client, ClientOuterClass.Client.Builder, ClientOuterClass.ClientOrBuilder> 
          getClienteleFieldBuilder() {
        if (clienteleBuilder_ == null) {
          clienteleBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              ClientOuterClass.Client, ClientOuterClass.Client.Builder, ClientOuterClass.ClientOrBuilder>(
                  clientele_,
                  ((bitField0_ & 0x00000004) != 0),
                  getParentForChildren(),
                  isClean());
          clientele_ = null;
        }
        return clienteleBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Server)
    }

    // @@protoc_insertion_point(class_scope:Server)
    private static final ServerOuterClass.Server DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ServerOuterClass.Server();
    }

    public static ServerOuterClass.Server getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Server>
        PARSER = new com.google.protobuf.AbstractParser<Server>() {
      @java.lang.Override
      public Server parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Server(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Server> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Server> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ServerOuterClass.Server getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Server_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Server_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023Server/Server.proto\032\025Article/Article.p" +
      "roto\032\023Client/Client.proto\"\204\001\n\006Server\022\017\n\007" +
      "address\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022!\n\017hosted_ar" +
      "ticles\030\003 \003(\0132\010.Article\022\034\n\013subscribers\030\004 " +
      "\003(\0132\007.Client\022\032\n\tclientele\030\005 \003(\0132\007.Client" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ArticleOuterClass.getDescriptor(),
          ClientOuterClass.getDescriptor(),
        });
    internal_static_Server_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Server_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Server_descriptor,
        new java.lang.String[] { "Address", "Name", "HostedArticles", "Subscribers", "Clientele", });
    ArticleOuterClass.getDescriptor();
    ClientOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
