# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Article/Article.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x41rticle/Article.proto\"1\n\x04\x44\x61te\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\x05\x12\r\n\x05month\x18\x02 \x01(\t\x12\x0c\n\x04year\x18\x03 \x01(\x05\"\x8c\x01\n\x07\x41rticle\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06\x61uthor\x18\x02 \x01(\t\x12\x13\n\x04time\x18\x03 \x01(\x0b\x32\x05.Date\x12\x0f\n\x07\x63ontent\x18\x04 \x01(\t\x12\x10\n\x06sports\x18\x05 \x01(\tH\x00\x12\x11\n\x07\x66\x61shion\x18\x06 \x01(\tH\x00\x12\x12\n\x08politics\x18\x07 \x01(\tH\x00\x42\x06\n\x04typeb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Article.Article_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DATE._serialized_start=25
  _DATE._serialized_end=74
  _ARTICLE._serialized_start=77
  _ARTICLE._serialized_end=217
# @@protoc_insertion_point(module_scope)
