# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RegistryServer/RegistryServer.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#RegistryServer/RegistryServer.proto\"o\n\x0eRegistryServer\x12-\n\x07servers\x18\x01 \x03(\x0b\x32\x1c.RegistryServer.ServersEntry\x1a.\n\x0cServersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RegistryServer.RegistryServer_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REGISTRYSERVER_SERVERSENTRY._options = None
  _REGISTRYSERVER_SERVERSENTRY._serialized_options = b'8\001'
  _REGISTRYSERVER._serialized_start=39
  _REGISTRYSERVER._serialized_end=150
  _REGISTRYSERVER_SERVERSENTRY._serialized_start=104
  _REGISTRYSERVER_SERVERSENTRY._serialized_end=150
# @@protoc_insertion_point(module_scope)
