# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: primaryBlocking/registry_server_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-primaryBlocking/registry_server_service.proto\"H\n\x16RegisterReplicaRequest\x12\x14\n\x0creplica_name\x18\x01 \x01(\t\x12\n\n\x02ip\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\x05\"o\n\x17RegisterReplicaResponse\x12\x1a\n\x12is_replica_primary\x18\x01 \x01(\x08\x12\x1a\n\x12primary_replica_ip\x18\x02 \x01(\t\x12\x1c\n\x14primary_replica_port\x18\x03 \x01(\x05\x32_\n\x15RegistryServerService\x12\x46\n\x0fRegisterReplica\x12\x17.RegisterReplicaRequest\x1a\x18.RegisterReplicaResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'primaryBlocking.registry_server_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REGISTERREPLICAREQUEST._serialized_start=49
  _REGISTERREPLICAREQUEST._serialized_end=121
  _REGISTERREPLICARESPONSE._serialized_start=123
  _REGISTERREPLICARESPONSE._serialized_end=234
  _REGISTRYSERVERSERVICE._serialized_start=236
  _REGISTRYSERVERSERVICE._serialized_end=331
# @@protoc_insertion_point(module_scope)
