# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import registry_server_service_pb2 as registry__server__service__pb2


class RegistryServerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterReplica = channel.unary_unary(
                '/RegistryServerService/RegisterReplica',
                request_serializer=registry__server__service__pb2.RegisterReplicaRequest.SerializeToString,
                response_deserializer=registry__server__service__pb2.RegisterReplicaResponse.FromString,
                )
        self.GetReplicaList = channel.unary_unary(
                '/RegistryServerService/GetReplicaList',
                request_serializer=registry__server__service__pb2.GetReplicaListRequest.SerializeToString,
                response_deserializer=registry__server__service__pb2.GetReplicaListResponse.FromString,
                )


class RegistryServerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterReplica(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetReplicaList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RegistryServerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterReplica': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterReplica,
                    request_deserializer=registry__server__service__pb2.RegisterReplicaRequest.FromString,
                    response_serializer=registry__server__service__pb2.RegisterReplicaResponse.SerializeToString,
            ),
            'GetReplicaList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReplicaList,
                    request_deserializer=registry__server__service__pb2.GetReplicaListRequest.FromString,
                    response_serializer=registry__server__service__pb2.GetReplicaListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'RegistryServerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RegistryServerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterReplica(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RegistryServerService/RegisterReplica',
            registry__server__service__pb2.RegisterReplicaRequest.SerializeToString,
            registry__server__service__pb2.RegisterReplicaResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetReplicaList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RegistryServerService/GetReplicaList',
            registry__server__service__pb2.GetReplicaListRequest.SerializeToString,
            registry__server__service__pb2.GetReplicaListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
