# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: primaryBlocking/status.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cprimaryBlocking/status.proto\"e\n\x06Status\x12!\n\x04type\x18\x01 \x01(\x0e\x32\x13.Status.STATUS_TYPE\x12\x0f\n\x07message\x18\x02 \x01(\t\"\'\n\x0bSTATUS_TYPE\x12\x0b\n\x07SUCCESS\x10\x00\x12\x0b\n\x07\x46\x41ILURE\x10\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'primaryBlocking.status_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STATUS._serialized_start=32
  _STATUS._serialized_end=133
  _STATUS_STATUS_TYPE._serialized_start=94
  _STATUS_STATUS_TYPE._serialized_end=133
# @@protoc_insertion_point(module_scope)
