# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mapper_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14mapper_service.proto\"N\n\nMapRequest\x12\r\n\x05query\x18\x01 \x01(\x05\x12\x16\n\x0einput_location\x18\x02 \x01(\t\x12\x19\n\x11input_split_files\x18\x03 \x03(\t\"\r\n\x0bMapResponse23\n\rMapperService\x12\"\n\x03map\x12\x0b.MapRequest\x1a\x0c.MapResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mapper_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MAPREQUEST._serialized_start=24
  _MAPREQUEST._serialized_end=102
  _MAPRESPONSE._serialized_start=104
  _MAPRESPONSE._serialized_end=117
  _MAPPERSERVICE._serialized_start=119
  _MAPPERSERVICE._serialized_end=170
# @@protoc_insertion_point(module_scope)
