# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import master_service_pb2 as master__service__pb2


class MasterServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterMapper = channel.unary_unary(
                '/MasterService/RegisterMapper',
                request_serializer=master__service__pb2.RegisterMapperRequest.SerializeToString,
                response_deserializer=master__service__pb2.RegisterMapperResponse.FromString,
                )
        self.RegisterReducer = channel.unary_unary(
                '/MasterService/RegisterReducer',
                request_serializer=master__service__pb2.RegisterReducerRequest.SerializeToString,
                response_deserializer=master__service__pb2.RegisterReducerResponse.FromString,
                )


class MasterServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterMapper(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterReducer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MasterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterMapper': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterMapper,
                    request_deserializer=master__service__pb2.RegisterMapperRequest.FromString,
                    response_serializer=master__service__pb2.RegisterMapperResponse.SerializeToString,
            ),
            'RegisterReducer': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterReducer,
                    request_deserializer=master__service__pb2.RegisterReducerRequest.FromString,
                    response_serializer=master__service__pb2.RegisterReducerResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MasterService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MasterService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterMapper(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MasterService/RegisterMapper',
            master__service__pb2.RegisterMapperRequest.SerializeToString,
            master__service__pb2.RegisterMapperResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RegisterReducer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MasterService/RegisterReducer',
            master__service__pb2.RegisterReducerRequest.SerializeToString,
            master__service__pb2.RegisterReducerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
