# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: master_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14master_service.proto\"1\n\x15RegisterMapperRequest\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\"\x80\x01\n\x16RegisterMapperResponse\x12\x13\n\x0bmapper_name\x18\x01 \x01(\t\x12.\n\x06status\x18\x02 \x01(\x0e\x32\x1e.RegisterMapperResponse.Status\"!\n\x06Status\x12\n\n\x06\x46\x41ILED\x10\x00\x12\x0b\n\x07SUCCESS\x10\x01\"2\n\x16RegisterReducerRequest\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\"\x83\x01\n\x17RegisterReducerResponse\x12\x14\n\x0creducer_name\x18\x01 \x01(\t\x12/\n\x06status\x18\x02 \x01(\x0e\x32\x1f.RegisterReducerResponse.Status\"!\n\x06Status\x12\n\n\x06\x46\x41ILED\x10\x00\x12\x0b\n\x07SUCCESS\x10\x01\x32\x9c\x01\n\rMasterService\x12\x43\n\x0eRegisterMapper\x12\x16.RegisterMapperRequest\x1a\x17.RegisterMapperResponse\"\x00\x12\x46\n\x0fRegisterReducer\x12\x17.RegisterReducerRequest\x1a\x18.RegisterReducerResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'master_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REGISTERMAPPERREQUEST._serialized_start=24
  _REGISTERMAPPERREQUEST._serialized_end=73
  _REGISTERMAPPERRESPONSE._serialized_start=76
  _REGISTERMAPPERRESPONSE._serialized_end=204
  _REGISTERMAPPERRESPONSE_STATUS._serialized_start=171
  _REGISTERMAPPERRESPONSE_STATUS._serialized_end=204
  _REGISTERREDUCERREQUEST._serialized_start=206
  _REGISTERREDUCERREQUEST._serialized_end=256
  _REGISTERREDUCERRESPONSE._serialized_start=259
  _REGISTERREDUCERRESPONSE._serialized_end=390
  _REGISTERREDUCERRESPONSE_STATUS._serialized_start=171
  _REGISTERREDUCERRESPONSE_STATUS._serialized_end=204
  _MASTERSERVICE._serialized_start=393
  _MASTERSERVICE._serialized_end=549
# @@protoc_insertion_point(module_scope)
