# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reducer_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15reducer_service.proto\"U\n\rReduceRequest\x12\r\n\x05query\x18\x01 \x01(\x05\x12\x1c\n\x14partition_files_path\x18\x02 \x03(\t\x12\x17\n\x0foutput_location\x18\x03 \x01(\t\"u\n\x0eReduceResponse\x12&\n\x06status\x18\x01 \x01(\x0e\x32\x16.ReduceResponse.Status\x12\x18\n\x10output_file_path\x18\x02 \x01(\t\"!\n\x06Status\x12\n\n\x06\x46\x41ILED\x10\x00\x12\x0b\n\x07SUCCESS\x10\x01\x32=\n\x0eReducerService\x12+\n\x06reduce\x12\x0e.ReduceRequest\x1a\x0f.ReduceResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'reducer_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REDUCEREQUEST._serialized_start=25
  _REDUCEREQUEST._serialized_end=110
  _REDUCERESPONSE._serialized_start=112
  _REDUCERESPONSE._serialized_end=229
  _REDUCERESPONSE_STATUS._serialized_start=196
  _REDUCERESPONSE_STATUS._serialized_end=229
  _REDUCERSERVICE._serialized_start=231
  _REDUCERSERVICE._serialized_end=292
# @@protoc_insertion_point(module_scope)
