# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Server/Server.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from Article import Article_pb2 as Article_dot_Article__pb2
from Client import Client_pb2 as Client_dot_Client__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13Server/Server.proto\x1a\x15\x41rticle/Article.proto\x1a\x13\x43lient/Client.proto\"\x84\x01\n\x06Server\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12!\n\x0fhosted_articles\x18\x03 \x03(\x0b\x32\x08.Article\x12\x1c\n\x0bsubscribers\x18\x04 \x03(\x0b\x32\x07.Client\x12\x1a\n\tclientele\x18\x05 \x03(\x0b\x32\x07.Clientb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Server.Server_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SERVER._serialized_start=68
  _SERVER._serialized_end=200
# @@protoc_insertion_point(module_scope)
