# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from grpc.server import server_pb2 as grpc_dot_server_dot_server__pb2


class ServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetArticles = channel.unary_unary(
                '/Server/GetArticles',
                request_serializer=grpc_dot_server_dot_server__pb2.GetArticlesRequest.SerializeToString,
                response_deserializer=grpc_dot_server_dot_server__pb2.GetArticlesResponse.FromString,
                )
        self.PublishArticle = channel.unary_unary(
                '/Server/PublishArticle',
                request_serializer=grpc_dot_server_dot_server__pb2.PublishArticleRequest.SerializeToString,
                response_deserializer=grpc_dot_server_dot_server__pb2.PublishArticleResponse.FromString,
                )


class ServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetArticles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PublishArticle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetArticles': grpc.unary_unary_rpc_method_handler(
                    servicer.GetArticles,
                    request_deserializer=grpc_dot_server_dot_server__pb2.GetArticlesRequest.FromString,
                    response_serializer=grpc_dot_server_dot_server__pb2.GetArticlesResponse.SerializeToString,
            ),
            'PublishArticle': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishArticle,
                    request_deserializer=grpc_dot_server_dot_server__pb2.PublishArticleRequest.FromString,
                    response_serializer=grpc_dot_server_dot_server__pb2.PublishArticleResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Server', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Server(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetArticles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Server/GetArticles',
            grpc_dot_server_dot_server__pb2.GetArticlesRequest.SerializeToString,
            grpc_dot_server_dot_server__pb2.GetArticlesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PublishArticle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Server/PublishArticle',
            grpc_dot_server_dot_server__pb2.PublishArticleRequest.SerializeToString,
            grpc_dot_server_dot_server__pb2.PublishArticleResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
