// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RegistryServer.proto

public final class RegistryServerOuterClass {
  private RegistryServerOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RegistryServerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RegistryServer)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>map&lt;string, string&gt; servers = 1;</code>
     */
    int getServersCount();
    /**
     * <code>map&lt;string, string&gt; servers = 1;</code>
     */
    boolean containsServers(
        java.lang.String key);
    /**
     * Use {@link #getServersMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getServers();
    /**
     * <code>map&lt;string, string&gt; servers = 1;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getServersMap();
    /**
     * <code>map&lt;string, string&gt; servers = 1;</code>
     */

    java.lang.String getServersOrDefault(
        java.lang.String key,
        java.lang.String defaultValue);
    /**
     * <code>map&lt;string, string&gt; servers = 1;</code>
     */

    java.lang.String getServersOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code RegistryServer}
   */
  public static final class RegistryServer extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:RegistryServer)
      RegistryServerOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RegistryServer.newBuilder() to construct.
    private RegistryServer(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RegistryServer() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new RegistryServer();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RegistryServer(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                servers_ = com.google.protobuf.MapField.newMapField(
                    ServersDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              servers__ = input.readMessage(
                  ServersDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              servers_.getMutableMap().put(
                  servers__.getKey(), servers__.getValue());
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return RegistryServerOuterClass.internal_static_RegistryServer_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetServers();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return RegistryServerOuterClass.internal_static_RegistryServer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              RegistryServerOuterClass.RegistryServer.class, RegistryServerOuterClass.RegistryServer.Builder.class);
    }

    public static final int SERVERS_FIELD_NUMBER = 1;
    private static final class ServersDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  RegistryServerOuterClass.internal_static_RegistryServer_ServersEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> servers_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetServers() {
      if (servers_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ServersDefaultEntryHolder.defaultEntry);
      }
      return servers_;
    }

    public int getServersCount() {
      return internalGetServers().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; servers = 1;</code>
     */

    @java.lang.Override
    public boolean containsServers(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetServers().getMap().containsKey(key);
    }
    /**
     * Use {@link #getServersMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getServers() {
      return getServersMap();
    }
    /**
     * <code>map&lt;string, string&gt; servers = 1;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, java.lang.String> getServersMap() {
      return internalGetServers().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; servers = 1;</code>
     */
    @java.lang.Override

    public java.lang.String getServersOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetServers().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; servers = 1;</code>
     */
    @java.lang.Override

    public java.lang.String getServersOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetServers().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetServers(),
          ServersDefaultEntryHolder.defaultEntry,
          1);
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetServers().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        servers__ = ServersDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, servers__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof RegistryServerOuterClass.RegistryServer)) {
        return super.equals(obj);
      }
      RegistryServerOuterClass.RegistryServer other = (RegistryServerOuterClass.RegistryServer) obj;

      if (!internalGetServers().equals(
          other.internalGetServers())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (!internalGetServers().getMap().isEmpty()) {
        hash = (37 * hash) + SERVERS_FIELD_NUMBER;
        hash = (53 * hash) + internalGetServers().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static RegistryServerOuterClass.RegistryServer parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RegistryServerOuterClass.RegistryServer parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RegistryServerOuterClass.RegistryServer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RegistryServerOuterClass.RegistryServer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RegistryServerOuterClass.RegistryServer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RegistryServerOuterClass.RegistryServer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RegistryServerOuterClass.RegistryServer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RegistryServerOuterClass.RegistryServer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static RegistryServerOuterClass.RegistryServer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static RegistryServerOuterClass.RegistryServer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static RegistryServerOuterClass.RegistryServer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RegistryServerOuterClass.RegistryServer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(RegistryServerOuterClass.RegistryServer prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RegistryServer}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:RegistryServer)
        RegistryServerOuterClass.RegistryServerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return RegistryServerOuterClass.internal_static_RegistryServer_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetServers();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetMutableServers();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return RegistryServerOuterClass.internal_static_RegistryServer_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                RegistryServerOuterClass.RegistryServer.class, RegistryServerOuterClass.RegistryServer.Builder.class);
      }

      // Construct using RegistryServerOuterClass.RegistryServer.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        internalGetMutableServers().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return RegistryServerOuterClass.internal_static_RegistryServer_descriptor;
      }

      @java.lang.Override
      public RegistryServerOuterClass.RegistryServer getDefaultInstanceForType() {
        return RegistryServerOuterClass.RegistryServer.getDefaultInstance();
      }

      @java.lang.Override
      public RegistryServerOuterClass.RegistryServer build() {
        RegistryServerOuterClass.RegistryServer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public RegistryServerOuterClass.RegistryServer buildPartial() {
        RegistryServerOuterClass.RegistryServer result = new RegistryServerOuterClass.RegistryServer(this);
        int from_bitField0_ = bitField0_;
        result.servers_ = internalGetServers();
        result.servers_.makeImmutable();
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof RegistryServerOuterClass.RegistryServer) {
          return mergeFrom((RegistryServerOuterClass.RegistryServer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(RegistryServerOuterClass.RegistryServer other) {
        if (other == RegistryServerOuterClass.RegistryServer.getDefaultInstance()) return this;
        internalGetMutableServers().mergeFrom(
            other.internalGetServers());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        RegistryServerOuterClass.RegistryServer parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (RegistryServerOuterClass.RegistryServer) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> servers_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetServers() {
        if (servers_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              ServersDefaultEntryHolder.defaultEntry);
        }
        return servers_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutableServers() {
        onChanged();;
        if (servers_ == null) {
          servers_ = com.google.protobuf.MapField.newMapField(
              ServersDefaultEntryHolder.defaultEntry);
        }
        if (!servers_.isMutable()) {
          servers_ = servers_.copy();
        }
        return servers_;
      }

      public int getServersCount() {
        return internalGetServers().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; servers = 1;</code>
       */

      @java.lang.Override
      public boolean containsServers(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetServers().getMap().containsKey(key);
      }
      /**
       * Use {@link #getServersMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getServers() {
        return getServersMap();
      }
      /**
       * <code>map&lt;string, string&gt; servers = 1;</code>
       */
      @java.lang.Override

      public java.util.Map<java.lang.String, java.lang.String> getServersMap() {
        return internalGetServers().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; servers = 1;</code>
       */
      @java.lang.Override

      public java.lang.String getServersOrDefault(
          java.lang.String key,
          java.lang.String defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetServers().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; servers = 1;</code>
       */
      @java.lang.Override

      public java.lang.String getServersOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetServers().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearServers() {
        internalGetMutableServers().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; servers = 1;</code>
       */

      public Builder removeServers(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableServers().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableServers() {
        return internalGetMutableServers().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; servers = 1;</code>
       */
      public Builder putServers(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableServers().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; servers = 1;</code>
       */

      public Builder putAllServers(
          java.util.Map<java.lang.String, java.lang.String> values) {
        internalGetMutableServers().getMutableMap()
            .putAll(values);
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:RegistryServer)
    }

    // @@protoc_insertion_point(class_scope:RegistryServer)
    private static final RegistryServerOuterClass.RegistryServer DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new RegistryServerOuterClass.RegistryServer();
    }

    public static RegistryServerOuterClass.RegistryServer getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RegistryServer>
        PARSER = new com.google.protobuf.AbstractParser<RegistryServer>() {
      @java.lang.Override
      public RegistryServer parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RegistryServer(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RegistryServer> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RegistryServer> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public RegistryServerOuterClass.RegistryServer getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RegistryServer_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RegistryServer_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RegistryServer_ServersEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RegistryServer_ServersEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024RegistryServer.proto\"o\n\016RegistryServer" +
      "\022-\n\007servers\030\001 \003(\0132\034.RegistryServer.Serve" +
      "rsEntry\032.\n\014ServersEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005" +
      "value\030\002 \001(\t:\0028\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_RegistryServer_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RegistryServer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RegistryServer_descriptor,
        new java.lang.String[] { "Servers", });
    internal_static_RegistryServer_ServersEntry_descriptor =
      internal_static_RegistryServer_descriptor.getNestedTypes().get(0);
    internal_static_RegistryServer_ServersEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RegistryServer_ServersEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
