# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RegistryServer.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='RegistryServer.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14RegistryServer.proto\"o\n\x0eRegistryServer\x12-\n\x07servers\x18\x01 \x03(\x0b\x32\x1c.RegistryServer.ServersEntry\x1a.\n\x0cServersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x62\x06proto3'
)




_REGISTRYSERVER_SERVERSENTRY = _descriptor.Descriptor(
  name='ServersEntry',
  full_name='RegistryServer.ServersEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='RegistryServer.ServersEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='RegistryServer.ServersEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=135,
)

_REGISTRYSERVER = _descriptor.Descriptor(
  name='RegistryServer',
  full_name='RegistryServer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='servers', full_name='RegistryServer.servers', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_REGISTRYSERVER_SERVERSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=135,
)

_REGISTRYSERVER_SERVERSENTRY.containing_type = _REGISTRYSERVER
_REGISTRYSERVER.fields_by_name['servers'].message_type = _REGISTRYSERVER_SERVERSENTRY
DESCRIPTOR.message_types_by_name['RegistryServer'] = _REGISTRYSERVER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RegistryServer = _reflection.GeneratedProtocolMessageType('RegistryServer', (_message.Message,), {

  'ServersEntry' : _reflection.GeneratedProtocolMessageType('ServersEntry', (_message.Message,), {
    'DESCRIPTOR' : _REGISTRYSERVER_SERVERSENTRY,
    '__module__' : 'RegistryServer_pb2'
    # @@protoc_insertion_point(class_scope:RegistryServer.ServersEntry)
    })
  ,
  'DESCRIPTOR' : _REGISTRYSERVER,
  '__module__' : 'RegistryServer_pb2'
  # @@protoc_insertion_point(class_scope:RegistryServer)
  })
_sym_db.RegisterMessage(RegistryServer)
_sym_db.RegisterMessage(RegistryServer.ServersEntry)


_REGISTRYSERVER_SERVERSENTRY._options = None
# @@protoc_insertion_point(module_scope)
